language: node_js
node_js:
  - 5
before_install:
  - npm install -g grunt-cli
env:
  global:
    secure: UFEgXXLsOARaVpRSJXHwDc8NydgrUGWcluyyLkZbp8d2bSChW2FRB/bjMtiiRoQiZrA+QnLpcS57OPSF8+n59Ywnu+pDN2ZGAe5s6x3ONniyuZDrruWAyqIM+t5aFiIQLZaTusD3Ep3QsQmSEbcaJdX3T3Yj4ZpZcNGt4alljLuQcvNKY9/RhYTuqfhwjgt9w+kH+fkoI47vwMKBDxzydqjDdn6FvxnEcUTzj+cBJxuNmbjAGZ26cy10zU717J65F+Z7J7Hgp4zwsE4tHpQfMBTkx3wCzJi/TEJRdmATHCGYnTMunnAql+Akc8q1pEABmllG5J4hCIfYR+VphtmtF22BvhRfXm351zsWKp43VCzCRMGCCDzG45GBrx3X/6HG9BpBhr12YvgY7hsnQUss4WT7FEMikq/GPQ1/4+AAl0ZYE6dblvA1m2G+QpY51Y5yv2n0hJ/3w6e2+Wy3Gl39qSuvcb4b1ZxXVZpiGoPjcyw34w1P7/yiCZxbhMf61TYG9JrKJf5w3FEjqexzhHOawEkAXUCLLX3sl6dB0DVFzDdngt5hovwf8ZU9lGhcxH0k+P9iCQjYPjC6RZKkLMUVuECl3ram3a4UAlWP0jfrN6VfMTMd7i6hnoUCn09AffFiEYmvalFPdckasULK+md/JKcKclw7IKZUv21Km4mW0Eo=
